---
deployment:
  tasks:
    - /bin/cp -rf /home/hetagayrimenkul/repositories/emlak/app /home/hetagayrimenkul/
    - /bin/cp -rf /home/hetagayrimenkul/repositories/emlak/public_html /home/hetagayrimenkul/
    - /bin/cp -rf /home/hetagayrimenkul/repositories/emlak/cron /home/hetagayrimenkul/
    - /bin/cp -rf /home/hetagayrimenkul/repositories/emlak/assets /home/hetagayrimenkul/
